#pragma once

#define SA_CLEAR_SCREEN_ON_START true
#define SA_CREATE_ANOTHER_TERMINAL true
#define SA_USE_NMAP_TO_SEARCH_SERVERS false
#define SA_PING_SERVER_BEFORE_CALL_SSH false
#define SA_PAUSE_AFTER_CALLING_SSH true
